# Light-Dark box configuration for scoring
default_start: DARK
states:
  - DARK
  - LIGHT
events:
  - name: GROOMING
    key: g
  - name: REARING
    key: r
  - name: STRETCH-ATTEND
    key: t
colors:
  DARK: '#ffeeaa'
  LIGHT: '#dddddd'
duration: 300
